// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonBb65af87DecodeHeadHunterInternalEntityModels(in *jlexer.Lexer, out *ExperienceDetail) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "resume_id":
			out.ResumeId = uint(in.Uint())
		case "is_current_job":
			out.IsCurrentJob = string(in.String())
		case "start_date":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.StartDate).UnmarshalJSON(data))
			}
		case "end_date":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.EndDate).UnmarshalJSON(data))
			}
		case "job_title":
			out.JobTitle = string(in.String())
		case "company_name":
			out.CompanyName = string(in.String())
		case "job_location_city":
			out.JobLocationCity = string(in.String())
		case "description":
			out.ExperienceDescription = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonBb65af87EncodeHeadHunterInternalEntityModels(out *jwriter.Writer, in ExperienceDetail) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"resume_id\":"
		out.RawString(prefix[1:])
		out.Uint(uint(in.ResumeId))
	}
	{
		const prefix string = ",\"is_current_job\":"
		out.RawString(prefix)
		out.String(string(in.IsCurrentJob))
	}
	{
		const prefix string = ",\"start_date\":"
		out.RawString(prefix)
		out.Raw((in.StartDate).MarshalJSON())
	}
	{
		const prefix string = ",\"end_date\":"
		out.RawString(prefix)
		out.Raw((in.EndDate).MarshalJSON())
	}
	{
		const prefix string = ",\"job_title\":"
		out.RawString(prefix)
		out.String(string(in.JobTitle))
	}
	{
		const prefix string = ",\"company_name\":"
		out.RawString(prefix)
		out.String(string(in.CompanyName))
	}
	{
		const prefix string = ",\"job_location_city\":"
		out.RawString(prefix)
		out.String(string(in.JobLocationCity))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.ExperienceDescription))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ExperienceDetail) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonBb65af87EncodeHeadHunterInternalEntityModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ExperienceDetail) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonBb65af87EncodeHeadHunterInternalEntityModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ExperienceDetail) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonBb65af87DecodeHeadHunterInternalEntityModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ExperienceDetail) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonBb65af87DecodeHeadHunterInternalEntityModels(l, v)
}
