FROM golang:1.19-alpine as builder
WORKDIR /backend
COPY . .
RUN apk add --update musl-dev libwebp-dev gcc
RUN go mod tidy
RUN sed -i 's/\r//g' builder/buildScript.sh
CMD ["sh", "builder/buildScript.sh"]
