version: '3.8'

services:
  backend:
    build: ./
    ports:
      - '8080:8080'
    container_name: server
    depends_on:
      - postgres
      - redis
    volumes:
      - ./data/image/avatar:/backend/data/image/avatar
  postgres:
    image: postgres:latest
    container_name: jfPostgres
    environment:
      POSTGRES_DB: "jobflowDB"
      POSTGRES_USER: "jobflowAdmin"
      POSTGRES_PASSWORD: "pgjf12345RTY"
    ports:
      - '5432:5432'
    volumes:
      - ./data/db:/var/lib/postgresql/data2
  redis:
    image: redis:latest
    container_name: jfRedis
    ports:
      - "6379:6379"
    command: >
      --requirepass rjf358123QWE
