version: '3.8'

services:
  backend:
    build: ./
    ports:
      - '8080:8080'
    container_name: server
    depends_on:
      - postgres
      - redis
      - auth
      - mail
    volumes:
      - ./data/image/avatar:/backend/data/image/avatar
  postgres:
    image: postgres:latest
    container_name: jfPostgres
    environment:
      POSTGRES_DB: "jobflowDB"
      POSTGRES_USER: "jobflowAdmin"
      #POSTGRES_PASSWORD: "pgjf12345RTY"
      POSTGRES_PASSWORD: "12345"
    ports:
      - '5432:5432'
    volumes:
      - ./data/db:/var/lib/postgresql/data2
  redis:
    image: redis:latest
    container_name: jfRedis
    ports:
      - "6379:6379"
    command: >
      --requirepass rjf358123QWE
  auth:
    build:
      context: .
      dockerfile: Dockerfile-auth
    container_name: auth_service
    depends_on:
      - redis
    ports:
      - "8081:8081"
  mail:
    build:
      context: .
      dockerfile: Dockerfile-mail
    container_name: mail_service
    depends_on:
      - redis
      - auth
    ports:
      - "8082:8082"
