version: '3.8'

services:
  backend:
    build: ./
    ports:
      - '8080:8080'
    container_name: server
    depends_on:
      - postgres
      - redis
      - auth
      - mail
    volumes:
      - ./data/image/avatar:/backend/data/image/avatar
  postgres:
    image: postgres:latest
    container_name: jfPostgres
    environment:
      POSTGRES_DB: "jobflowDB"
      POSTGRES_USER: "jobflowAdmin"
      POSTGRES_PASSWORD: "pgjf12345RTY"
    ports:
      - '5432:5432'
    volumes:
      - ./data/db:/var/lib/postgresql/data2
  redis:
    image: redis:latest
    container_name: jfRedis
    ports:
      - "6379:6379"
    command: >
      --requirepass rjf358123QWE
  auth:
    build:
      context: .
      dockerfile: Dockerfile-auth
    container_name: auth_service
    depends_on:
      - redis
    ports:
      - "8081:8081"
  mail:
    build:
      context: .
      dockerfile: Dockerfile-mail
    container_name: mail_service
    depends_on:
      - redis
      - auth
    ports:
      - "8082:8082"
  prometheus:
    container_name: "jfPrometheus"
    image: "prom/prometheus"
    ports:
      - "9090:9090"
    depends_on:
      - nodeexporter
    volumes:
      - ./metrics/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    container_name: "jfGrafana"
    image: "grafana/grafana-enterprise"
    depends_on:
      - prometheus
    volumes:
      - ./data/grafana:/var/lib/grafana
    command:
      - 'git clone https://github.com/grafana/piechart-panel.git --branch release-1.6.2'
      - 'sudo service grafana-server restart'
    ports:
      - "3000:3000"

  nodeexporter:
    container_name: "jfNodeExporter"
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'
    ports:
      - "9100:9100"