version: '3.8'

services:
  prometheus:
    container_name: "jfPrometheus"
    image: "prom/prometheus"
    ports:
      - "9090:9090"
    depends_on:
      - nodeexporter
    volumes:
      - ./metrics/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    container_name: "jfGrafana"
    image: "grafana/grafana-enterprise"
    depends_on:
      - prometheus
    volumes:
      - ./data/grafana:/var/lib/grafana
    ports:
      - "3000:3000"

  nodeexporter:
    container_name: "jfNodeExporter"
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'
    ports:
      - "9100:9100"
