version: '3.8'

services:
  backend:
    build: ./
    ports:
      - '8080:8080'
    container_name: server
    depends_on:
      builder:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      auth:
        condition: service_started
      mail:
        condition: service_started
    volumes:
      - ./data/image/avatar:/backend/data/image/avatar
      - ./bin:/backend/bin

  postgres:
    image: postgres:latest
    container_name: jfPostgres
    environment:
      POSTGRES_DB: "jobflowDB"
      POSTGRES_USER: "jobflowAdmin"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    volumes:
      - ./data/db:/var/lib/postgresql/data2

  redis:
    image: redis:latest
    container_name: jfRedis
    ports:
      - "6379:6379"
    command: >
      --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli","ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  auth:
    build:
      context: .
      dockerfile: Dockerfile-auth
    container_name: auth_service
    depends_on:
      builder:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    ports:
      - "8081:8081"
    volumes:
      - ./bin:/auth/bin

  mail:
    build:
      context: .
      dockerfile: Dockerfile-mail
    container_name: mail_service
    depends_on:
      builder:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
      auth:
        condition: service_started
    ports:
      - "8082:8082"
    volumes:
      - ./bin:/mail/bin
  builder:
    ports:
      - "8085:8085"
    build:
      context: .
      dockerfile: Dockerfile-builder
    container_name: builder
    volumes:
      - ./bin:/backend/bin
