domain: "mail_service"
port: ":8082"
authMsHost: "auth_service"
authMsPort: ":8081"
metricPath: "/metrics"
metricPort: ":8092"
mail:
  username: "jobflow@jobflow.su"
  password: "393hLfdbwzuMxEJ775PC"
  host: "smtp.mail.ru"
  port: 587
db:
  username: "jobflowAdmin"
  host: "jfPostgres"
  port: "5432"
  dbname: "jobflowDB"
  sslmode: "disable"