domain: "localhost"
port: ":8080"
defaultExpiringSession: 12
db:
  username: "jobflowAdmin"
  host: "jfPostgres"
  port: "5432"
  dbname: "jobflowDB"
  sslmode: "disable"
  password: "12345"
redis:
  host: "jfRedis"
  port: "6379"
  password: "rjf358123QWE"
  dbname: "sessionDB"