domain: "localhost"
port: ":8080"
defaultExpiringSession: 259200
authDomain: "auth_service"
authPort: ":8081"
mailDomain: "mail_service"
mailPort: ":8082"
db:
  username: "jobflowAdmin"
  host: "jfPostgres"
  port: "5432"
  dbname: "jobflowDB"
  sslmode: "disable"
  #password: "pgjf12345RTY"
  password: "12345"
validation:
  minNameLength: 2
  maxNameLength: 30
  minSurnameLength: 2
  maxSurnameLength: 30
  minPasswordLength: 8
  maxPasswordLength: 20
  minEmailLength: 8
  maxEmailLength: 30
  minResumeTitleLength: 3
  maxResumeTitleLength: 30
  minResumeDescriptionLength: 3
cookie:
  httpOnly: true
  secure: false
crypt:
  cost: 10
image:
  path: "data/image/"
  defaultEmployerAvatar: "basic_employer_avatar"
  defaultApplicantAvatar: "basic_applicant_avatar"
security:
  csrfSecret: "jobFlowSecretWorld112351235125"
  csrfMode: false
  confirmationTime: 600
  confirmAccountMode: true
