domain: "localhost"
port: ":8080"
defaultExpiringSession: 259200
authMsHost: "auth_service"
authMsPort: ":8081"
mailMsHost: "mail_service"
mailMsPort: ":8082"
metricPath: "/metrics"
cleaningPeriod: 2
db:
  username: "jobflowAdmin"
  host: "jfPostgres"
  port: "5432"
  dbname: "jobflowDB"
  sslmode: "disable"
validation:
  minNameLength: 2
  maxNameLength: 30
  minSurnameLength: 2
  maxSurnameLength: 30
  minPasswordLength: 8
  maxPasswordLength: 20
  minEmailLength: 8
  maxEmailLength: 30
  minResumeTitleLength: 3
  maxResumeTitleLength: 30
  minResumeDescriptionLength: 3
cookie:
  httpOnly: true
  secure: false
crypt:
  cost: 10
image:
  path: "data/image/"
  defaultEmployerAvatar: "basic_employer_avatar"
  defaultApplicantAvatar: "basic_applicant_avatar"
  defaultAverageColor: "28, 52, 236"
security:
  csrfSecret: "jobFlowSecretWorld112351235125"
  csrfMode: false
  confirmationTime: 600
  confirmAccountMode: true
pdf:
  htmlPath: "/usr/share/html/"
  zoomSize: 1
