// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: mail.proto

package handler

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MailServiceClient is the client API for MailService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MailServiceClient interface {
	SendConfirmCode(ctx context.Context, in *Email, opts ...grpc.CallOption) (*Nothing, error)
	SendApplicantMailing(ctx context.Context, in *ApplicantMailingData, opts ...grpc.CallOption) (*Nothing, error)
	SendEmployerMailing(ctx context.Context, in *EmployerMailingData, opts ...grpc.CallOption) (*Nothing, error)
}

type mailServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMailServiceClient(cc grpc.ClientConnInterface) MailServiceClient {
	return &mailServiceClient{cc}
}

func (c *mailServiceClient) SendConfirmCode(ctx context.Context, in *Email, opts ...grpc.CallOption) (*Nothing, error) {
	out := new(Nothing)
	err := c.cc.Invoke(ctx, "/mail.MailService/SendConfirmCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailServiceClient) SendApplicantMailing(ctx context.Context, in *ApplicantMailingData, opts ...grpc.CallOption) (*Nothing, error) {
	out := new(Nothing)
	err := c.cc.Invoke(ctx, "/mail.MailService/SendApplicantMailing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mailServiceClient) SendEmployerMailing(ctx context.Context, in *EmployerMailingData, opts ...grpc.CallOption) (*Nothing, error) {
	out := new(Nothing)
	err := c.cc.Invoke(ctx, "/mail.MailService/SendEmployerMailing", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MailServiceServer is the server API for MailService service.
// All implementations must embed UnimplementedMailServiceServer
// for forward compatibility
type MailServiceServer interface {
	SendConfirmCode(context.Context, *Email) (*Nothing, error)
	SendApplicantMailing(context.Context, *ApplicantMailingData) (*Nothing, error)
	SendEmployerMailing(context.Context, *EmployerMailingData) (*Nothing, error)
	mustEmbedUnimplementedMailServiceServer()
}

// UnimplementedMailServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMailServiceServer struct {
}

func (UnimplementedMailServiceServer) SendConfirmCode(context.Context, *Email) (*Nothing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendConfirmCode not implemented")
}
func (UnimplementedMailServiceServer) SendApplicantMailing(context.Context, *ApplicantMailingData) (*Nothing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendApplicantMailing not implemented")
}
func (UnimplementedMailServiceServer) SendEmployerMailing(context.Context, *EmployerMailingData) (*Nothing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEmployerMailing not implemented")
}
func (UnimplementedMailServiceServer) mustEmbedUnimplementedMailServiceServer() {}

// UnsafeMailServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MailServiceServer will
// result in compilation errors.
type UnsafeMailServiceServer interface {
	mustEmbedUnimplementedMailServiceServer()
}

func RegisterMailServiceServer(s grpc.ServiceRegistrar, srv MailServiceServer) {
	s.RegisterService(&MailService_ServiceDesc, srv)
}

func _MailService_SendConfirmCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Email)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServiceServer).SendConfirmCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mail.MailService/SendConfirmCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServiceServer).SendConfirmCode(ctx, req.(*Email))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailService_SendApplicantMailing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplicantMailingData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServiceServer).SendApplicantMailing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mail.MailService/SendApplicantMailing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServiceServer).SendApplicantMailing(ctx, req.(*ApplicantMailingData))
	}
	return interceptor(ctx, in, info, handler)
}

func _MailService_SendEmployerMailing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmployerMailingData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServiceServer).SendEmployerMailing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mail.MailService/SendEmployerMailing",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServiceServer).SendEmployerMailing(ctx, req.(*EmployerMailingData))
	}
	return interceptor(ctx, in, info, handler)
}

// MailService_ServiceDesc is the grpc.ServiceDesc for MailService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MailService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mail.MailService",
	HandlerType: (*MailServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendConfirmCode",
			Handler:    _MailService_SendConfirmCode_Handler,
		},
		{
			MethodName: "SendApplicantMailing",
			Handler:    _MailService_SendApplicantMailing_Handler,
		},
		{
			MethodName: "SendEmployerMailing",
			Handler:    _MailService_SendEmployerMailing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mail.proto",
}
