name: Jobflow CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Download library
        run: sudo apt-get update; sudo apt-get install libwebp-dev;

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build -v ./...

      - name: Run go vet
        run: go vet ./...

      - name: Run go test
        run: go test $(go list ./... | grep -v vendor) -race -coverprofile=coverage.out

      - name: Coverage report
        run: go tool cover -func=coverage.out
