name: Jobflow CI


on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Download library
        run: sudo apt-get update; sudo apt-get install libwebp-dev;

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build -v ./...

      - name: Run go vet
        run: go vet ./...
        
      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.45.2

      - name: Run linter
        run: golangci-lint run

      - name: Run go test
        run: go test $(go list ./... | grep -v vendor) -race -coverprofile=coverage.out.tmp; cat coverage.out.tmp | grep -v ".pb.go | grep -v "_easyjson.go"" > coverage.out

      - name: Coverage report
        run: go tool cover -func=coverage.out
