name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    
    - name: Download library
      run: sudo apt-get update; sudo apt-get install libwebp-dev;
      
    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build -v ./...
      
    - name: Run go vet
      run: go vet ./...
      
    - name: Run tests
      run: go test ./...
      
    - name: Docker-compose up
      run: ls;sudo docker stop $(docker ps -aq);sudo docker-compose up -d;
      
          
